[build]
  # Set the directory where Netlify will look for the build output
  publish = "dist"
  # Specify the build command for Nuxt.js (usually `npm run build` or `yarn build`)
  command = "npm run build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"