[build]
  # Set the directory where Netlify will look for the build output
  publish = "dist"
  # Specify the build command for Nuxt.js
  command = "yarn cache clean && yarn install && yarn build"
  environment = { NODE_VERSION = "20" }

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
